import { PrismaClient } from '@prisma/client';

const db = new PrismaClient();

interface ProductData {
  name: string;
  category: string;
  gender: string;
  intensity: string;
  occasion: string;
  olfactiveFamily: string;
  fixation: string;
  projection?: string;
  price: number;
  costPrice: number;
  notesKey: string;
  notesTop?: string;
  notesHeart?: string;
  notesBase?: string;
  description: string;
  isFeatured?: boolean;
  isNew?: boolean;
  isBestseller?: boolean;
  isKit?: boolean;
  kitContents?: string;
  forWho?: string;
  sortOrder?: number;
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

const products: ProductData[] = [
  {
    name: "Fakhar Rose",
    category: "feminino",
    gender: "feminino",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "floral",
    fixation: "6-8 horas",
    price: 45,
    costPrice: 19,
    notesKey: "Rosa, Peônia, Almíscar",
    description: "Elegância floral em um frasco. A linha Fakhar traz sofisticação com notas de rosa e peônia.",
    forWho: "Para ela",
    sortOrder: 1,
  },
  {
    name: "Fakhar Gold",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 45,
    costPrice: 19,
    notesKey: "Âmbar, Oud, Sândalo",
    description: "Ousadia dourada. Uma fragrância rica e envolvente com toque oriental.",
    forWho: "Para todos",
    sortOrder: 2,
  },
  {
    name: "Fakhar Black",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "fougère",
    fixation: "6-8 horas",
    price: 45,
    costPrice: 19,
    notesKey: "Maçã, Gengibre, Sálvia, Âmbar",
    description: "A elegância masculina em um frasco. Inspirado no Y de YSL, é fresco, limpo e muito versátil para o dia a dia.",
    forWho: "Para ele",
    sortOrder: 3,
  },
  {
    name: "Fakhar Platinum",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "trabalho",
    olfactiveFamily: "cítrico",
    fixation: "6-8 horas",
    price: 45,
    costPrice: 19,
    notesKey: "Bergamota, Cedro, Vetiver",
    description: "Sophistication in platinum. A fresh, woody fragrance for the modern gentleman.",
    forWho: "Para ele",
    sortOrder: 4,
  },
  {
    name: "Yara Rosa",
    category: "feminino",
    gender: "feminino",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "floral",
    fixation: "6-8 horas",
    price: 38.90,
    costPrice: 18.50,
    notesKey: "Morango, Baunilha, Almíscar",
    description: "O queridinho das redes sociais. Um perfume cremoso, feminino e viciante que remete a um milkshake de morango sofisticado.",
    isBestseller: true,
    forWho: "Para ela",
    sortOrder: 5,
  },
  {
    name: "Yara Candy",
    category: "feminino",
    gender: "feminino",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "gourmet",
    fixation: "6-8 horas",
    price: 38.90,
    costPrice: 18.50,
    notesKey: "Frutas Vermelhas, Marshmallow, Baunilha",
    description: "Uma explosão de frutas doces e balas de goma. É a versão mais jovem e divertida da linha Yara.",
    forWho: "Para ela",
    sortOrder: 6,
  },
  {
    name: "Yara Moi",
    category: "feminino",
    gender: "feminino",
    intensity: "moderada",
    occasion: "trabalho",
    olfactiveFamily: "amadeirado",
    fixation: "6-8 horas",
    price: 38.90,
    costPrice: 18.50,
    notesKey: "Pêssego, Jasmim, Caramelo, Sândalo",
    description: "Mais sofisticado que o Rosa, foca no pêssego e caramelo com um fundo amadeirado. Elegante para o trabalho.",
    forWho: "Para ela",
    sortOrder: 7,
  },
  {
    name: "Yara Tous",
    category: "feminino",
    gender: "feminino",
    intensity: "leve",
    occasion: "verão",
    olfactiveFamily: "aquático",
    fixation: "4-6 horas",
    price: 38.90,
    costPrice: 18.50,
    notesKey: "Manga, Coco, Maracujá",
    description: "Cheiro de férias! Mistura manga com coco. Um perfume solar que exala alegria.",
    forWho: "Para ela",
    sortOrder: 8,
  },
  {
    name: "Asad Tradicional",
    category: "masculino",
    gender: "masculino",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "especiado",
    fixation: "8-12 horas",
    price: 38.90,
    costPrice: 18.50,
    notesKey: "Pimenta Preta, Café, Patchouli",
    description: "Considerado um dos melhores clones do Sauvage Elixir. É intenso, amadeirado e perfeito para quem busca presença.",
    isBestseller: true,
    forWho: "Para ele",
    sortOrder: 9,
  },
  {
    name: "Asad Bourbon",
    category: "masculino",
    gender: "masculino",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "8-12 horas",
    price: 38.90,
    costPrice: 18.50,
    notesKey: "Notas de Rum, Patchouli, Âmbar",
    description: "Versão mais densa e noturna, com toques que lembram bebidas finas e especiarias. Extremamente sedutor.",
    forWho: "Para ele",
    sortOrder: 10,
  },
  {
    name: "Asad Zanzibar",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "verão",
    olfactiveFamily: "aquático",
    fixation: "6-8 horas",
    price: 38.90,
    costPrice: 19,
    notesKey: "Água de Coco, Íris, Sal Marinho",
    description: "Uma variação fresca e exótica do Asad original, com um toque de água de coco e sal marinho.",
    isNew: true,
    forWho: "Para ele",
    sortOrder: 11,
  },
  {
    name: "Asad Zanzibar Limited Edition",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "verão",
    olfactiveFamily: "oriental",
    fixation: "8-12 horas",
    price: 38.90,
    costPrice: 19,
    notesKey: "Água de Coco, Especiarias, Oud",
    description: "Edição limitada exclusiva. Uma versão aprimorada do Zanzibar com mais profundidade e fixação.",
    isNew: true,
    forWho: "Para ele",
    sortOrder: 12,
  },
  {
    name: "Ana Abiyedh Rouge",
    category: "feminino",
    gender: "feminino",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "floral",
    fixation: "6-8 horas",
    price: 42,
    costPrice: 16,
    notesKey: "Rosa, Jasmim, Almíscar",
    description: "Elegância e feminilidade em cada borrifada. Um floral sofisticado para mulheres que gostam de presença.",
    isBestseller: true,
    forWho: "Para ela",
    sortOrder: 13,
  },
  {
    name: "Ana Abiyedh Scarlet",
    category: "feminino",
    gender: "feminino",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "8-12 horas",
    price: 42,
    costPrice: 16,
    notesKey: "Açafrão, Rosa, Âmbar",
    description: "Uma fragrância marcante e envolvente. Scarlet é para quem quer ser notada.",
    forWho: "Para ela",
    sortOrder: 14,
  },
  {
    name: "Ana Abiyedh Poudre",
    category: "feminino",
    gender: "feminino",
    intensity: "leve",
    occasion: "dia",
    olfactiveFamily: "floral",
    fixation: "4-6 horas",
    price: 42,
    costPrice: 16,
    notesKey: "Notas Atalcadas, Almíscar, Baunilha",
    description: "Delicado como um abraço. Tem aquele cheiro de pele limpa e maquiagem cara, muito confortável.",
    isBestseller: true,
    forWho: "Para ela",
    sortOrder: 15,
  },
  {
    name: "Her Confession",
    category: "feminino",
    gender: "feminino",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "8-12 horas",
    price: 60,
    costPrice: 30,
    notesKey: "Rosa, Oud, Baunilha, Sândalo",
    description: "A confissão feminina mais sedutora. Uma fragrância que revela a essência da mulher moderna.",
    isFeatured: true,
    forWho: "Para ela",
    sortOrder: 16,
  },
  {
    name: "His Confession",
    category: "masculino",
    gender: "masculino",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "amadeirado",
    fixation: "8-12 horas",
    price: 60,
    costPrice: 30,
    notesKey: "Oud, Âmbar, Especiarias, Almíscar",
    description: "A confissão masculina mais poderosa. Uma fragrância de autoridade e sofisticação.",
    isFeatured: true,
    forWho: "Para ele",
    sortOrder: 17,
  },
  {
    name: "Amerat Al Arab Sugar",
    category: "feminino",
    gender: "feminino",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "floral",
    fixation: "6-8 horas",
    price: 40,
    costPrice: 17,
    notesKey: "Jasmim, Rosa, Açúcar Mascavo",
    description: "Como o nome diz, é uma versão açucarada e ultra feminina do Amerat clássico. Um floral com toque de mel.",
    forWho: "Para ela",
    sortOrder: 18,
  },
  {
    name: "Amerat Al Arab",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 40,
    costPrice: 16,
    notesKey: "Oud, Rosa, Almíscar, Âmbar",
    description: "A essência da perfumaria árabe. Uma fragrância nobre e atemporal.",
    forWho: "Para todos",
    sortOrder: 19,
  },
  {
    name: "Petra",
    category: "unissex",
    gender: "unissex",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "amadeirado",
    fixation: "12+ horas",
    price: 65,
    costPrice: 28,
    notesKey: "Oud, Rosa, Âmbar, Almíscar",
    description: "Como a cidade histórica, Petra é monumental. Uma fragrância de nicho com Oud premium.",
    isFeatured: true,
    forWho: "Para todos",
    sortOrder: 20,
  },
  {
    name: "Badee Al Oud Blush",
    category: "feminino",
    gender: "feminino",
    intensity: "intensa",
    occasion: "festa",
    olfactiveFamily: "floral",
    fixation: "8-12 horas",
    price: 48.90,
    costPrice: 21,
    notesKey: "Rosa, Baunilha, Notas Talcadas",
    description: "Inspirado no Delina Exclusif. Uma rosa cremosa, doce e potente. Fixação eterna na pele.",
    isBestseller: true,
    forWho: "Para ela",
    sortOrder: 21,
  },
  {
    name: "Badee Al Oud Glory",
    category: "unissex",
    gender: "unissex",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "8-12 horas",
    price: 48.90,
    costPrice: 21,
    notesKey: "Açafrão, Nutmeg, Oud, Patchouli",
    description: "Misterioso e opulento. Uma fragrância de nicho focada no Oud, para quem gosta de perfumes marcantes e secos.",
    isFeatured: true,
    forWho: "Para todos",
    sortOrder: 22,
  },
  {
    name: "Badee Al Oud Sublime",
    category: "unissex",
    gender: "unissex",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "amadeirado",
    fixation: "12+ horas",
    price: 48.90,
    costPrice: 21,
    notesKey: "Oud, Sândalo, Almíscar, Patchouli",
    description: "Sublimidade em um frasco. A versão mais intensa da linha Badee Al Oud.",
    forWho: "Para todos",
    sortOrder: 23,
  },
  {
    name: "Badee Al Oud Amethyst",
    category: "feminino",
    gender: "feminino",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "floral",
    fixation: "8-12 horas",
    price: 48.90,
    costPrice: 21,
    notesKey: "Rosa, Violeta, Oud, Baunilha",
    description: "A beleza da ametista traduzida em fragrância. Floral, místico e envolvente.",
    forWho: "Para ela",
    sortOrder: 24,
  },
  {
    name: "Badee Al Oud Honor",
    category: "masculino",
    gender: "masculino",
    intensity: "intensa",
    occasion: "trabalho",
    olfactiveFamily: "amadeirado",
    fixation: "8-12 horas",
    price: 48.90,
    costPrice: 21,
    notesKey: "Oud, Pimenta, Cedro, Almíscar",
    description: "Honra e tradição. Uma fragrância masculina com Oud de alta qualidade.",
    forWho: "Para ele",
    sortOrder: 25,
  },
  {
    name: "Eclaire Caramel",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "gourmet",
    fixation: "6-8 horas",
    price: 48.90,
    costPrice: 24,
    notesKey: "Caramelo, Açúcar, Leite",
    description: "Uma fragrância puramente comestível. Doce na medida certa, remetendo a sobremesas finas de caramelo.",
    isBestseller: true,
    forWho: "Para todos",
    sortOrder: 26,
  },
  {
    name: "Eclaire Banoffi",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "gourmet",
    fixation: "6-8 horas",
    price: 48.90,
    costPrice: 24,
    notesKey: "Banana, Caramelo, Creme",
    description: "Inspired by the famous banoffee pie. Gourmand, comforting and addictive.",
    forWho: "Para todos",
    sortOrder: 27,
  },
  {
    name: "Eclaire Pistache",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "gourmet",
    fixation: "6-8 horas",
    price: 48.90,
    costPrice: 24,
    notesKey: "Pistache, Creme de Leite, Amêndoas",
    description: "Fragrâncias que remetem diretamente a sobremesas. O de Pistache é a grande tendência do momento.",
    isNew: true,
    forWho: "Para todos",
    sortOrder: 28,
  },
  {
    name: "Al Noble Wazeer",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 38.90,
    costPrice: 19,
    notesKey: "Hortelã, Chocolate, Âmbar",
    description: "Uma mistura equilibrada de frescor frutado com uma base séria de chocolate e sândalo. Muito versátil.",
    forWho: "Para ele",
    sortOrder: 29,
  },
  {
    name: "Al Noble Safeer",
    category: "masculino",
    gender: "masculino",
    intensity: "leve",
    occasion: "dia",
    olfactiveFamily: "cítrico",
    fixation: "4-6 horas",
    price: 38.90,
    costPrice: 19,
    notesKey: "Notas Verdes, Artemísia, Cominho",
    description: "Um perfume verde, refrescante e aromático. Passa uma imagem de limpeza e sofisticação natural.",
    forWho: "Para ele",
    sortOrder: 30,
  },
  {
    name: "Al Noble Ameer",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "noite",
    olfactiveFamily: "amadeirado",
    fixation: "8-12 horas",
    price: 38.90,
    costPrice: 19,
    notesKey: "Oud, Âmbar, Especiarias",
    description: "A nobreza em forma de fragrância. Uma composição oriental sofisticada para homens de destaque.",
    forWho: "Para ele",
    sortOrder: 31,
  },
  {
    name: "Mussamam White",
    category: "unissex",
    gender: "unissex",
    intensity: "leve",
    occasion: "dia",
    olfactiveFamily: "cítrico",
    fixation: "6-8 horas",
    price: 70,
    costPrice: 30,
    notesKey: "Bergamota, Lavanda, Sândalo",
    description: "Sofisticado e iluminado. Traz uma sensação de limpeza luxuosa e frescor cítrico que dura o dia todo.",
    isFeatured: true,
    isBestseller: true,
    forWho: "Para todos",
    sortOrder: 32,
  },
  {
    name: "Mussamam Black",
    category: "masculino",
    gender: "masculino",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "amadeirado",
    fixation: "12+ horas",
    price: 70,
    costPrice: 35,
    notesKey: "Pimenta, Couro, Notas Amadeiradas",
    description: "Um perfume dark e sofisticado. Lembra o luxo do couro e incenso. Para quem quer um cheiro de autoridade.",
    isFeatured: true,
    forWho: "Para ele",
    sortOrder: 33,
  },
  {
    name: "Khamrah",
    category: "unissex",
    gender: "unissex",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "gourmet",
    fixation: "8-12 horas",
    price: 40,
    costPrice: 21.50,
    notesKey: "Tâmaras, Canela, Pralinê, Baunilha",
    description: "Uma explosão de tâmaras e canela. Quente, doce e extremamente elegante. Ideal para noites e climas frios.",
    isBestseller: true,
    forWho: "Para todos",
    sortOrder: 34,
  },
  {
    name: "Angham",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 50,
    costPrice: 25,
    notesKey: "Rosa, Oud, Almíscar",
    description: "Harmonia em cada nota. Uma fragrância que equilibra floral e oriental com maestria.",
    forWho: "Para todos",
    sortOrder: 35,
  },
  {
    name: "Angham Second Song",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 50,
    costPrice: 30,
    notesKey: "Oud, Sândalo, Baunilha, Patchouli",
    description: "O segundo movimento de Angham. Mais profundo, mais amadeirado, mais envolvente.",
    forWho: "Para todos",
    sortOrder: 36,
  },
  {
    name: "Sakeena",
    category: "feminino",
    gender: "feminino",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 48.90,
    costPrice: 21,
    notesKey: "Maracujá, Framboesa, Pralinê",
    description: "Um perfume de nicho em frasco acessível. Mistura notas de ozônio, maracujá e pralinê. Diferente de tudo.",
    forWho: "Para ela",
    sortOrder: 37,
  },
  {
    name: "Emaan",
    category: "feminino",
    gender: "feminino",
    intensity: "leve",
    occasion: "dia",
    olfactiveFamily: "floral",
    fixation: "6-8 horas",
    price: 48.90,
    costPrice: 21,
    notesKey: "Jasmim, Peônia, Almíscar, Baunilha",
    description: "Fé e beleza. Uma fragrância feminina delicada e reconfortante.",
    forWho: "Para ela",
    sortOrder: 38,
  },
  {
    name: "Maahir",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "cítrico",
    fixation: "6-8 horas",
    price: 50,
    costPrice: 22.50,
    notesKey: "Limão, Hortelã, Alecrim, Ambroxan",
    description: "O perfume do homem destemido. Fresco, cítrico e com personalidade marcante.",
    forWho: "Para ele",
    sortOrder: 39,
  },
  {
    name: "Maahir Legacy",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "verão",
    olfactiveFamily: "cítrico",
    fixation: "8-12 horas",
    price: 50,
    costPrice: 22.50,
    notesKey: "Limão, Hortelã, Alecrim, Ambroxan",
    description: "Inspirado no Sedley, é um perfume extremamente refrescante, ideal para o verão brasileiro ou português.",
    isBestseller: true,
    forWho: "Para ele",
    sortOrder: 40,
  },
  {
    name: "Nebras Elixir",
    category: "unissex",
    gender: "unissex",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "12+ horas",
    price: 60,
    costPrice: 30,
    notesKey: "Oud, Rosa, Âmbar, Almíscar",
    description: "Lanterna da noite. Um elixir oriental poderoso e duradouro.",
    isFeatured: true,
    forWho: "Para todos",
    sortOrder: 41,
  },
  {
    name: "Nardo Red",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "floral",
    fixation: "6-8 horas",
    price: 38.90,
    costPrice: 19,
    notesKey: "Rosa, Especiarias, Oud",
    description: "A intensidade do vermelho em fragrância. Um floral picante e marcante.",
    forWho: "Para todos",
    sortOrder: 42,
  },
  {
    name: "Shaheen Silver",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "amadeirado",
    fixation: "6-8 horas",
    price: 50,
    costPrice: 22,
    notesKey: "Bergamota, Cedro, Almíscar, Âmbar",
    description: "A prata do falcão. Elegância masculina com frescor e sofisticação.",
    forWho: "Para ele",
    sortOrder: 43,
  },
  {
    name: "Mishlah",
    category: "unissex",
    gender: "unissex",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "8-12 horas",
    price: 50,
    costPrice: 22,
    notesKey: "Oud, Rosa, Sândalo, Âmbar",
    description: "O manto da realeza. Uma fragrância oriental rica e majestosa.",
    forWho: "Para todos",
    sortOrder: 44,
  },
  {
    name: "Habik",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "floral",
    fixation: "6-8 horas",
    price: 50,
    costPrice: 22,
    notesKey: "Jasmim, Sândalo, Almíscar",
    description: "O seu amor. Uma fragrância envolvente e acolhedora.",
    forWho: "Para todos",
    sortOrder: 45,
  },
  {
    name: "Hayaati Al Maleky",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "festa",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 40,
    costPrice: 16,
    notesKey: "Noz-moscada, Cardamomo, Lavanda",
    description: "Um perfume azul e doce, muito elogiado pelo público feminino em homens. Excelente para festas.",
    forWho: "Para ele",
    sortOrder: 46,
  },
  {
    name: "Durrah",
    category: "unissex",
    gender: "unissex",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "12+ horas",
    price: 80,
    costPrice: 40,
    notesKey: "Oud Premium, Rosa, Âmbar, Almíscar",
    description: "A pérola mais valiosa. Uma fragrância de luxo absoluto para momentos especiais.",
    isFeatured: true,
    forWho: "Para todos",
    sortOrder: 47,
  },
  {
    name: "Sherif",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "amadeirado",
    fixation: "6-8 horas",
    price: 39.50,
    costPrice: 18.50,
    notesKey: "Oud, Especiarias, Almíscar",
    description: "A nobreza árabe em fragrância. Sofisticado e marcante.",
    forWho: "Para ele",
    sortOrder: 48,
  },
  {
    name: "Rage",
    category: "masculino",
    gender: "masculino",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "especiado",
    fixation: "8-12 horas",
    price: 39.50,
    costPrice: 18.50,
    notesKey: "Pimenta, Oud, Patchouli",
    description: "A fúria elegante. Uma fragrância intensa e marcante para noites memoráveis.",
    forWho: "Para ele",
    sortOrder: 49,
  },
  {
    name: "Ajayeb Dubai",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 39.50,
    costPrice: 18.50,
    notesKey: "Oud, Âmbar, Especiarias",
    description: "As maravilhas de Dubai em um frasco. Exótico e sofisticado.",
    forWho: "Para todos",
    sortOrder: 50,
  },
  {
    name: "Ajwad",
    category: "masculino",
    gender: "masculino",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "amadeirado",
    fixation: "6-8 horas",
    price: 39.50,
    costPrice: 18.50,
    notesKey: "Cedro, Bergamota, Almíscar",
    description: "Generosidade em fragrância. Um perfume masculino versátil e elegante.",
    forWho: "Para ele",
    sortOrder: 51,
  },
  {
    name: "Liquid Brun",
    category: "unissex",
    gender: "unissex",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "gourmet",
    fixation: "8-12 horas",
    price: 69.90,
    costPrice: 25,
    notesKey: "Chocolate, Café, Baunilha, Oud",
    description: "A escuridão do prazer. Uma fragrância gourmet intensa com notas de chocolate e café.",
    isFeatured: true,
    forWho: "Para todos",
    sortOrder: 52,
  },
  {
    name: "Signature White",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "floral",
    fixation: "6-8 horas",
    price: 150,
    costPrice: 60,
    notesKey: "Bergamota, Jasmim, Almíscar, Sândalo",
    description: "A assinatura da Alma Lik. Uma fragrância premium que define a identidade da marca.",
    isFeatured: true,
    forWho: "Para todos",
    sortOrder: 53,
  },
  {
    name: "Signature Brown",
    category: "unissex",
    gender: "unissex",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "amadeirado",
    fixation: "12+ horas",
    price: 150,
    costPrice: 60,
    notesKey: "Oud, Âmbar, Baunilha, Patchouli",
    description: "A assinatura escura da Alma Lik. Oud premium com profundidade e fixação extraordinárias.",
    isFeatured: true,
    forWho: "Para todos",
    sortOrder: 54,
  },
  {
    name: "Royal Amber",
    category: "unissex",
    gender: "unissex",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "12+ horas",
    price: 120,
    costPrice: 65,
    notesKey: "Âmbar, Oud, Rosa, Almíscar",
    description: "O âmbar da realeza. Uma fragrância oriental de alta fixação e projeção.",
    isFeatured: true,
    forWho: "Para todos",
    sortOrder: 55,
  },
  {
    name: "Ambar Rouge",
    category: "unissex",
    gender: "unissex",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "12+ horas",
    price: 120,
    costPrice: 65,
    notesKey: "Âmbar, Canela, Oud, Especiarias",
    description: "O âmbar vermelho da paixão. Uma fragrância picante e envolvente.",
    forWho: "Para todos",
    sortOrder: 56,
  },
  {
    name: "Rose Éclat",
    category: "feminino",
    gender: "feminino",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "floral",
    fixation: "8-12 horas",
    price: 120,
    costPrice: 65,
    notesKey: "Rosa Premium, Peônia, Almíscar, Âmbar",
    description: "O esplendor da rosa. Uma fragrância floral premium com fixação impressionante.",
    forWho: "Para ela",
    sortOrder: 57,
  },
  {
    name: "Imperial Jade",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 132.50,
    costPrice: 70,
    notesKey: "Bergamota, Jasmim, Sândalo, Almíscar",
    description: "O jade imperial. Frescor e sofisticação em uma composição equilibrada.",
    forWho: "Para todos",
    sortOrder: 58,
  },
  {
    name: "Azure Fantasy",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "verão",
    olfactiveFamily: "aquático",
    fixation: "6-8 horas",
    price: 132.50,
    costPrice: 70,
    notesKey: "Notas Marinhas, Jasmim, Cedro, Almíscar",
    description: "A fantasia azul. Um perfume aquático com profundidade oriental.",
    forWho: "Para todos",
    sortOrder: 59,
  },
  {
    name: "Nardo Oud",
    category: "unissex",
    gender: "unissex",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "amadeirado",
    fixation: "12+ horas",
    price: 132.50,
    costPrice: 70,
    notesKey: "Oud, Nardo, Âmbar, Patchouli",
    description: "A combinação perfeita de Nardo e Oud. Intenso, duradouro e sofisticado.",
    forWho: "Para todos",
    sortOrder: 60,
  },
  {
    name: "Vulcan Black",
    category: "masculino",
    gender: "masculino",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "amadeirado",
    fixation: "12+ horas",
    price: 46.90,
    costPrice: 35,
    notesKey: "Couro, Pimenta, Oud, Âmbar",
    description: "A força do vulcão. Uma fragrância masculina intensa e imponente.",
    forWho: "Para ele",
    sortOrder: 61,
  },
  {
    name: "Vulcan Sable",
    category: "unissex",
    gender: "unissex",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "8-12 horas",
    price: 46.90,
    costPrice: 35,
    notesKey: "Âmbar, Sândalo, Especiarias",
    description: "A areia do deserto em fragrância. Quente e envolvente.",
    forWho: "Para todos",
    sortOrder: 62,
  },
  {
    name: "Vulcan Feu",
    category: "unissex",
    gender: "unissex",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "especiado",
    fixation: "12+ horas",
    price: 46.90,
    costPrice: 35,
    notesKey: "Pimenta, Canela, Oud, Patchouli",
    description: "O fogo da paixão. Uma fragrância picante e ardente.",
    forWho: "Para todos",
    sortOrder: 63,
  },
  {
    name: "Vulcan Baie",
    category: "feminino",
    gender: "feminino",
    intensity: "moderada",
    occasion: "dia",
    olfactiveFamily: "floral",
    fixation: "6-8 horas",
    price: 46.90,
    costPrice: 35,
    notesKey: "Frutas Vermelhas, Rosa, Baunilha",
    description: "A baía da beleza. Floral frutado, delicado e feminino.",
    forWho: "Para ela",
    sortOrder: 64,
  },
  {
    name: "Rayhaan Tiger",
    category: "masculino",
    gender: "masculino",
    intensity: "intensa",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "8-12 horas",
    price: 69,
    costPrice: 25,
    notesKey: "Oud, Âmbar, Especiarias, Almíscar",
    description: "O tigre da fragrância. Uma fragrância poderosa e imponente.",
    isNew: true,
    forWho: "Para ele",
    sortOrder: 65,
  },
  {
    name: "Black Obsidian",
    category: "unissex",
    gender: "unissex",
    intensity: "muito intensa",
    occasion: "noite",
    olfactiveFamily: "amadeirado",
    fixation: "12+ horas",
    price: 90,
    costPrice: 40,
    notesKey: "Oud Premium, Patchouli, Âmbar, Almíscar",
    description: "A obsidiana negra. Uma fragrância misteriosa e envolvente de alta performance.",
    isFeatured: true,
    forWho: "Para todos",
    sortOrder: 66,
  },
  {
    name: "Atmosphere",
    category: "unissex",
    gender: "unissex",
    intensity: "moderada",
    occasion: "versátil",
    olfactiveFamily: "cítrico",
    fixation: "6-8 horas",
    price: 90,
    costPrice: 40,
    notesKey: "Bergamota, Cedro, Almíscar, Sândalo",
    description: "A atmosfera perfeita. Uma fragrância versátil que cria presença em qualquer ambiente.",
    forWho: "Para todos",
    sortOrder: 67,
  },
  // KITS
  {
    name: "Kit Art of Nature",
    category: "kit",
    gender: "unissex",
    intensity: "variado",
    occasion: "dia",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 70,
    costPrice: 36,
    notesKey: "Múltiplas fragrâncias",
    description: "A arte da natureza em um kit exclusivo. Quatro fragrâncias que celebram a beleza natural.",
    isKit: true,
    kitContents: "4 fragrâncias selecionadas da coleção",
    forWho: "Para todos",
    sortOrder: 68,
  },
  {
    name: "Kit Pisa",
    category: "kit",
    gender: "unissex",
    intensity: "variado",
    occasion: "dia",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 70,
    costPrice: 36,
    notesKey: "Múltiplas fragrâncias",
    description: "Inspirado na elegância italiana. Um kit com fragrâncias sofisticadas.",
    isKit: true,
    kitContents: "4 fragrâncias selecionadas da coleção",
    forWho: "Para todos",
    sortOrder: 69,
  },
  {
    name: "Kit Al Qiam",
    category: "kit",
    gender: "unissex",
    intensity: "variado",
    occasion: "dia",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 70,
    costPrice: 36,
    notesKey: "Múltiplas fragrâncias",
    description: "A ascensão da fragrância. Um kit com as melhores composições.",
    isKit: true,
    kitContents: "4 fragrâncias selecionadas da coleção",
    forWho: "Para todos",
    sortOrder: 70,
  },
  {
    name: "Kit Radio",
    category: "kit",
    gender: "unissex",
    intensity: "variado",
    occasion: "dia",
    olfactiveFamily: "oriental",
    fixation: "6-8 horas",
    price: 70,
    costPrice: 36,
    notesKey: "Múltiplas fragrâncias",
    description: "Frequência da elegância. Um kit de fragrâncias que sintonizam com seu estilo.",
    isKit: true,
    kitContents: "4 fragrâncias selecionadas da coleção",
    forWho: "Para todos",
    sortOrder: 71,
  },
  {
    name: "Kit Badee Al Oud",
    category: "kit",
    gender: "unissex",
    intensity: "variado",
    occasion: "noite",
    olfactiveFamily: "oriental",
    fixation: "8-12 horas",
    price: 59.90,
    costPrice: 25,
    notesKey: "Oud, Patchouli, Rosa, Âmbar",
    description: "A trilogia do Oud. Três fragrâncias da icônica linha Badee Al Oud em um kit exclusivo.",
    isKit: true,
    kitContents: "3 fragrâncias da linha Badee Al Oud",
    forWho: "Para todos",
    sortOrder: 72,
  },
  {
    name: "Kit Maahir",
    category: "kit",
    gender: "masculino",
    intensity: "variado",
    occasion: "dia",
    olfactiveFamily: "cítrico",
    fixation: "6-8 horas",
    price: 59.90,
    costPrice: 25,
    notesKey: "Limão, Hortelã, Alecrim, Ambroxan",
    description: "A dupla do frescor. Maahir e Maahir Legacy em um kit irresistível.",
    isKit: true,
    kitContents: "2 fragrâncias da linha Maahir",
    forWho: "Para ele",
    sortOrder: 73,
  },
  {
    name: "Kit Fakhar",
    category: "kit",
    gender: "unissex",
    intensity: "variado",
    occasion: "versátil",
    olfactiveFamily: "fougère",
    fixation: "6-8 horas",
    price: 59.90,
    costPrice: 25,
    notesKey: "Múltiplas notas",
    description: "A elegância da linha Fakhar em um kit exclusivo.",
    isKit: true,
    kitContents: "3 fragrâncias da linha Fakhar",
    forWho: "Para todos",
    sortOrder: 74,
  },
  {
    name: "Kit Yara Rosa",
    category: "kit",
    gender: "feminino",
    intensity: "variado",
    occasion: "dia",
    olfactiveFamily: "floral",
    fixation: "6-8 horas",
    price: 60,
    costPrice: 30,
    notesKey: "Morango, Baunilha, Frutas",
    description: "A doçura da linha Yara em um kit perfeito para presentear.",
    isKit: true,
    kitContents: "3 fragrâncias da linha Yara",
    forWho: "Para ela",
    sortOrder: 75,
  },
  {
    name: "Kit Asad",
    category: "kit",
    gender: "masculino",
    intensity: "variado",
    occasion: "noite",
    olfactiveFamily: "especiado",
    fixation: "8-12 horas",
    price: 60,
    costPrice: 30,
    notesKey: "Pimenta, Café, Patchouli, Oud",
    description: "A força da linha Asad em um kit para quem busca presença.",
    isKit: true,
    kitContents: "3 fragrâncias da linha Asad",
    forWho: "Para ele",
    sortOrder: 76,
  },
];

async function main() {
  console.log(`🌱 Seeding ${products.length} products...`);

  // Clear existing data
  await db.orderItem.deleteMany();
  await db.order.deleteMany();
  await db.review.deleteMany();
  await db.product.deleteMany();

  for (const p of products) {
    await db.product.create({
      data: {
        name: p.name,
        slug: slugify(p.name),
        brand: "Alma Lik",
        description: p.description,
        price: p.price,
        costPrice: p.costPrice,
        category: p.category,
        gender: p.gender,
        intensity: p.intensity,
        occasion: p.occasion,
        olfactiveFamily: p.olfactiveFamily,
        fixation: p.fixation,
        projection: p.projection || "moderada",
        notesTop: p.notesTop || "",
        notesHeart: p.notesHeart || "",
        notesBase: p.notesBase || "",
        notesKey: p.notesKey,
        forWho: p.forWho || "Para todos",
        isFeatured: p.isFeatured || false,
        isNew: p.isNew || false,
        isBestseller: p.isBestseller || false,
        isKit: p.isKit || false,
        kitContents: p.kitContents || "",
        sortOrder: p.sortOrder || 0,
        stock: 50,
        rating: 4.5,
      },
    });
  }

  console.log(`✅ Successfully seeded ${products.length} products!`);

  // Print summary
  const counts = await db.product.groupBy({
    by: ['category'],
    _count: true,
  });
  console.log('\n📊 Product counts by category:');
  for (const c of counts) {
    console.log(`  ${c.category}: ${c._count}`);
  }
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect());
